<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>Assets\z-transcribe.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\z-transcribe.ico" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ZTranscribe.Core\ZTranscribe.Core.csproj" />
    <ProjectReference Include="..\ZTranscribe.Infrastructure\ZTranscribe.Infrastructure.csproj" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.10.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>
</Project>
